apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-pipeline
spec:
  # serviceAccountName: pipeline
  pipelineRef:
    name: build-iperf-server
  inputs:
    resources:
      - name: source
        resourceRef:
          name: iperf-git
  outputs:
    resources:
      - name: image
        resourceRef:
          name: iperf-server