kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: container-layers-spring-rest
  namespace: iperfcon
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-nfs-storage