apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: quay.io/ooichman/ubi-minimal
      command:
        - echo
      args:
        - "Hello World"